[toolchain]
channel = "1.82.0"
components = ["cargo", "clippy", "rustfmt"]
targets = [
    "aarch64-apple-ios", # iOS arm64
    "x86_64-apple-ios", # iOS x86_64

    "aarch64-apple-darwin", # mac M1
    "x86_64-apple-darwin", # mac x86_64
]
profile = "minimal"
